#!/bin/sh
#uci -q get dhcp.odhcpd && exit 0
DEFAULT_NAME="brbox" #short name for automate-box
#DEF_LAN_IP="192.168.8.1"
MACADDR=brb0x
echo -e "$MACADDR\n$MACADDR" | passwd root #MACID is the default root-pw 
uci -q batch <<-EOT
	set wireless.radio0.disabled=1
	set system.@system[0].hostname=$DEFAULT_NAME
	set dhcp.lan.ignore=1
	set dhcp.lan.dhcpv6=disabled
	set dhcp.lan.ra=disabled
	commit 
EOT
