#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=79
#APP=sysmgr
SERVICE_WRITE_PID=0
SERVICE_DAEMONIZE=0

#after linux boot, keep the led OFF to save power
start() {
        echo 0 > /sys/class/leds/a5-v11\:red\:power/brightness
}

#when rebooting, keep the led ON
stop() {
        echo 1 > /sys/class/leds/a5-v11\:red\:power/brightness
}
